version: "3"
services:
  web:
    container_name: caddy-dev
    command: caddy -agree -quic -conf=/etc/caddy/Caddyfile-dev
    ports:
      - "2015:2015"
    build:
      context: .
    deploy:
      mode: global
